### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by zhuangya** [portwatcher/Simple-Contact#2]
真厉害，但是来个 demo 嘛~

**Comment by portwatcher** [comment]
那尼？

**Comment by zhuangya** [comment]
只是说，放出来一个 demo 在网上 :)

feel free to close it if you don't want to.

**Comment by portwatcher** [comment]
thank you for notification :-)

I just upload a demo to my blog, you can check the [demo](http://www.pwhack.me/examples/simplecontact) now.
